%global _hardened_build 1

Name: vala-panel
Version: 0.3.8
Release: 1%{?dist}
License: LGPL-3.0+
Summary: Vala Panel is GTK+ 3 desktop panel. It is based on Vala and some LXPanel ideas
URL: https://github.com/rilian-la-te/vala-panel

Source0: https://github.com/rilian-la-te/%{name}/releases/download/%{version}/%{name}-%{version}.tar.gz
Patch0: 0001-cmake-don-t-build-applets-and-set-vala-0.32-because-.patch

BuildRequires: cmake >= 2.8.0
BuildRequires: gettext
BuildRequires: vala >= 0.32.0
BuildRequires: pkgconfig(gtk+-3.0) >= 3.20.0
BuildRequires: pkgconfig(libpeas-1.0) >= 1.2.0
BuildRequires: pkgconfig(libwnck-3.0) >= 3.4.0
Requires:      %{name}-libs

%description
Vala Panel is GTK+ 3 desktop panel. It is based on Vala and LXPanel ideas.
It was be a fork of LXPanel in version 0.1.0, but in 0.2.0 it is
completely rewritten in Vala. It offers same functionality as LXPanel, but:
1. It has slightly more memory usage.
2. X11 dependency is stripped from panel core (but it is not tested on
   another display servers, such as Wayland or Mir, right now).
3. Some of former LXPanel plugins is separate binaries now
   and lives in another packages (Example is volume applet).


%package libs
Summary: Common libs for %{name}

%description libs
Common libs for %{name}


%package devel
Summary: Shared library for %{name} - development files
Requires: %{name} = %{version}
Requires: pkgconfig

%description devel
Vala Panel is GTK+ 3 desktop panel. It is based on Vala and LXPanel ideas.
This is a development files for %{name}.


%prep
%autosetup -p1

%build
%cmake -DGSETTINGS_COMPILE=OFF
%make_build

%install
%make_install DESTDIR=%{buildroot}
%find_lang %{name}

%clean
rm -rf %{buildroot}

%post
/sbin/ldconfig

%postun
/sbin/ldconfig
if [ $1 -eq 0 ] ; then
    /usr/bin/glib-compile-schemas %{_datadir}/glib-2.0/schemas &> /dev/null || :
fi

%posttrans
/usr/bin/glib-compile-schemas %{_datadir}/glib-2.0/schemas &> /dev/null || :


%files -f %{name}.lang
%doc README.md
%license LICENSE
%{_mandir}/man1/vala-panel.1*
%{_bindir}/vala-panel
%{_bindir}/vala-panel-new
%{_bindir}/vala-panel-runner
%config(noreplace) %{_sysconfdir}/xdg/vala-panel
%{_datadir}/icons/hicolor/scalable/apps/vala-panel.svg
%{_datadir}/vala-panel/images/
%{_datadir}/glib-2.0/schemas/org.valapanel.builtin.gschema.xml
%{_datadir}/glib-2.0/schemas/org.valapanel.gschema.xml
%{_datadir}/glib-2.0/schemas/org.valapanel.toplevel.gschema.xml


%files libs
%{_libdir}/libvalapanel.so.*

%files devel
%{_includedir}/vala-panel/
%{_libdir}/libvalapanel.so
%{_libdir}/pkgconfig/vala-panel.pc
%{_libdir}/vala-panel/*.so*
%{_datadir}/vala/vapi/vala-panel.*


%changelog
* Sun Apr 16 2017 La Ode Muh. Fadlun Akbar <fadlun.net@gmail.com> - 0.3.8-1
- update spec file

* Mon Apr 27 2015 Konstantin <ria.freelander@gmail.com> - 0.3.8
  Generated by CMake UseRPMTools macros
