%global _hardened_build 1

Name:    vala-panel-appmenu
Version: 0.5.2
Release: 3%{?dist}
License: LGPL-3.0+
Summary: This package provides Application Menu plugin for vala-panel
URL:     https://github.com/rilian-la-te/vala-panel-appmenu

Source0: https://github.com/rilian-la-te/vala-panel-appmenu/releases/download/%{version}/%{name}-%{version}.tar.gz
Patch0:  backporting-from-master.patch

BuildRequires: cmake >= 2.8.0
BuildRequires: gettext
BuildRequires: vala >= 0.32.0
BuildRequires: pkgconfig(gtk+-2.0) >= 2.24.0
BuildRequires: pkgconfig(gtk+-3.0) >= 3.20.0
BuildRequires: pkgconfig(libpeas-1.0) >= 1.2.0
BuildRequires: pkgconfig(libbamf3)
BuildRequires: pkgconfig(libmatepanelapplet-4.0)
BuildRequires: pkgconfig(libxfce4panel-2.0)
BuildRequires: pkgconfig(libxfconf-0)
BuildRequires: pkgconfig(libwnck-3.0) >= 3.4.0
BuildRequires: pkgconfig(x11)
BuildRequires: pkgconfig(dbusmenu-glib-0.4)

Provides: vala-panel-appmenu-plugin

Requires: bamf-daemon
Requires: libdbusmenu
Requires: libdbusmenu-gtk2
Requires: libdbusmenu-gtk3
Requires: unity-gtk2-module
Requires: unity-gtk-module-common
Requires: unity-gtk3-module
Requires: appmenu-qt
Requires: appmenu-qt5
Requires: appmenu-qt5-profile.d

%description
This is Application Menu (Global Menu) plugin.
It built using Unity protocol and libraries,
and share all Unity limitations and advancements.


%package -n mate-vala-panel-appmenu-plugin
Summary:  This package provides Application Menu plugin for mate-panel
Requires: bamf-daemon
Requires: libdbusmenu
Requires: libdbusmenu-gtk2
Requires: libdbusmenu-gtk3
Requires: unity-gtk2-module
Requires: unity-gtk-module-common
Requires: unity-gtk3-module
Requires: appmenu-qt
Requires: appmenu-qt5
Requires: appmenu-qt5-profile.d
Provides: vala-panel-appmenu-plugin

%description -n mate-vala-panel-appmenu-plugin
This is Application Menu (Global Menu) plugin.
It built using Unity protocol and libraries,
and share all Unity limitations and advancements.


%package -n xfce4-vala-panel-appmenu-plugin
Summary:  This package provides Application Menu plugin for xfce4-panel
Requires: bamf-daemon
Requires: libdbusmenu
Requires: libdbusmenu-gtk2
Requires: libdbusmenu-gtk3
Requires: unity-gtk2-module
Requires: unity-gtk-module-common
Requires: unity-gtk3-module
Requires: appmenu-qt
Requires: appmenu-qt5
Requires: appmenu-qt5-profile.d
Provides: vala-panel-appmenu-plugin

%description -n xfce4-vala-panel-appmenu-plugin
This is Application Menu (Global Menu) plugin.
It built using Unity protocol and libraries,
and share all Unity limitations and advancements.


%prep
%autosetup -p1

%build
%cmake -DGSETTINGS_COMPILE=OFF -DENABLE_XFCE=ON -DENABLE_VALAPANEL=OFF \
       -DENABLE_BUDGIE=OFF -DENABLE_MATE=ON
%make_build

%install
%make_install DESTDIR=%{buildroot}
%find_lang %{name}

%{__mkdir} -p %{buildroot}%{_userunitdir}/default.target.wants
%{_bindir}/ln -s %{_userunitdir}/%{name}.service \
                %{buildroot}%{_userunitdir}/default.target.wants/%{name}.service

%postun
if [ $1 -eq 0 ] ; then
    /usr/bin/glib-compile-schemas %{_datadir}/glib-2.0/schemas &> /dev/null || :
fi

%posttrans
/usr/bin/glib-compile-schemas %{_datadir}/glib-2.0/schemas &> /dev/null || :

%clean
rm -rf %{buildroot}


%files -f %{name}.lang
%doc README.md
%license LICENSE
%{_userunitdir}/default.target.wants/%{name}.service

%files -n mate-vala-panel-appmenu-plugin
%{_datadir}/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service
%{_datadir}/mate-panel/applets/org.vala-panel.appmenu.mate-panel-applet
%{_libexecdir}/mate-panel/appmenu-mate

%files -n xfce4-vala-panel-appmenu-plugin
%{_libdir}/xfce4/panel/plugins/libappmenu-xfce.so
%{_datadir}/xfce4/panel/plugins/appmenu.desktop

%changelog
* Sat Jul 15 2017 La Ode Muh. Fadlun Akbar <fadlun.net@gmail.com> - 0.5.2-3
- Fix wrong dependencies name

* Thu Jul 13 2017 La Ode Muh. Fadlun Akbar <fadlun.net@gmail.com> - 0.5.2-2
- Don't build budgie plugin

* Thu Jul 13 2017 La Ode Muh. Fadlun Akbar <fadlun.net@gmail.com> - 0.5.2-1
- build budgie plugin
- update spec file

* Sun Apr 16 2017 La Ode Muh. Fadlun Akbar <fadlun.net@gmail.com> - 0.4.4-1
- update spec file

* Mon Apr 27 2015 Konstantin <ria.freelander@gmail.com> - 0.4.4
- Generated by CMake UseRPMTools macros
